const ActionTypes ={
    // get card
    GET_CARDHOTEL : "GET_CARDHTEL",
    GET_CARDHOTEL_SUCCED : "GET_CARDHTEL_SUCCED",
    GET_CARDHOTEL_FAILED : "GET_CARDHTEL_FAILED",

    // get faciallhotel
    GET_FACIALLHOTEL : "GET_FACIALLHOTEL",
    GET_FACIALLHOTEL_SUCCED : "GET_FACIALLHOTEL_SUCCED",
    GET_FACIALLHOTEL_FAILED : "GET_FACIALLHOTEL_FAILED",

    // get hore
    GET_HORE : "GET_HORE",
    GET_HORE_SUCCED : "GET_HORE_SUCCED",
    GET_HORE_FAILED : "GET_HORE_FAILED",

    // get adminHotel
    GET_HOTELADMIN : "GET_HOTELADMIN",
    GET_HOTELADMIN_SUCCED : "GET_HOTELADMIN_SUCCED",
    GET_HOTELADMIN_FAILED : "GET_HOTELADMIN_FAILED",

    // add hotel admin
    ADD_HOTELADMIN : "ADD_HOTELADMIN",
    ADD_HOTELADMIN_SUCCED : "ADD_HOTELADMIN_SUCCED",
    ADD_HOTELADMIN_FAILED : "ADD_HOTELADMIN_FAILED",

    // delete hotel
    DEL_HOTELADMIN :"DEL_HOTELADMIN",
    DEL_HOTELADMIN_SUCCED :"DEL_HOTELADMIN_SUCCED",
    DEL_HOTELADMIN_FAILED :"DEL_HOTELADMIN_FAIED",
    

}

export default ActionTypes