const ActionTypes ={
    // get card
    GET_CARDHOTEL : "GET_CARDHTEL",
    GET_CARDHOTEL_SUCCED : "GET_CARDHTEL_SUCCED",
    GET_CARDHOTEL_FAILED : "GET_CARDHTEL_FAILED",

    // get faciallhotel
    GET_FACIALLHOTEL : "GET_FACIALLHOTEL",
    GET_FACIALLHOTEL_SUCCED : "GET_FACIALLHOTEL_SUCCED",
    GET_FACIALLHOTEL_FAILED : "GET_FACIALLHOTEL_FAILED",

    // get hore
    GET_HORE : "GET_HORE",
    GET_HORE_SUCCED : "GET_HORE_SUCCED",
    GET_HORE_FAILED : "GET_HORE_FAILED"
   
    

}

export default ActionTypes