const ActionTypes ={
    // get card
    GET_CARDHOTEL : "GET_CARDHTEL",
    GET_CARDHOTEL_SUCCED : "GET_CARDHTEL_SUCCED",
    GET_CARDHOTEL_FAILED : "GET_CARDHTEL_FAILED",
    // get id card
    GET_IDCARDHOTEL : "GET_CARDHTEL",
    GET_IDCARDHOTEL_SUCCED : "GET_CARDHTEL_SUCCED",
    GET_IDCARDHOTEL_FAILED : "GET_CARDHTEL_FAILED",

}

export default ActionTypes