import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Slideshow from './components/slideshow'
import CardHotel from './components/cardHotel'
import { useEffect } from 'react'
import { useDispatch } from 'react-redux'
import { doCardHotelReq } from '@/redux/action/actionHotel'
import SearchHotel from './components/search'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const dispatch = useDispatch()
  useEffect(() => {
    dispatch(doCardHotelReq())
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Slideshow/>
        <SearchHotel/>
        <section id='hotels' className='mt-10'>
        <h1 className='text-center bold mb-10'>HOTELS</h1>
        <div className='flex flex-wrap md:flex-no-wrap -mx-3 items-center justify-center gap-6 m-10 '>
          <CardHotel/>
        </div>
        </section>
      </main>
    </>
  )
}
